### ISSUE TITLE
it tooks too much memory,is it all right?

### ISSUE THREAD

**Issue by panchengj** [OffchainLabs/eth-pos-devnet#1]
![C8BABBA8-1BCD-4176-90EF-84EDE77291DC](https://user-images.githubusercontent.com/13955506/200988679-3a5bfe78-a8c7-4889-adab-f203c7f1dd4c.png)

after run:
git clone https://github.com/rauljordan/eth-pos-devnet && cd eth-pos-devnet
docker compose up

it will take over my 64G memory machine in a day ,is it all right?

**Comment by macrocan** [comment]
I had also same issue

**Comment by rauljordan** [comment]
Hi @panchengj we believe we have fixed the memory leaks since then. Try again with a `make clean` and `docker compose up -d`
