### ISSUE TITLE
Beacon chain memory is constantly increasing

### ISSUE THREAD

**Issue by youngseoka** [OffchainLabs/eth-pos-devnet#23]
Running this project as a docker will continue to increase beacon chain memory and terminate.. Can you give me a hint on how to solve this problem??
![메모리가터져버려~](https://github.com/OffchainLabs/eth-pos-devnet/assets/33947681/8819f06a-6532-4377-a8d4-6a6420a343d4)

**Comment by youngseoka** [comment]
http://localhost:6060/debug/pprof/
screenshot
![debug pprof](https://github.com/OffchainLabs/eth-pos-devnet/assets/33947681/fead1249-33f3-4796-9991-a42c187140da)


http://localhost:6060/debug/pprof/heap?debug=1
text is too many so i upload page to txt
[heap.txt](https://github.com/OffchainLabs/eth-pos-devnet/files/11672856/heap.txt)

**Comment by youngseoka** [comment]
@nisdas cant

can't surrpot that file type so upload zip

By the way, how can I open this file and check it? I want to know the result, too. And thank you for helping me. I am surprised by your knowledge. Thank you very much.

[heap.zip](https://github.com/OffchainLabs/eth-pos-devnet/files/11697629/heap.zip)

**Comment by nisdas** [comment]
```
go tool pprof -http localhost:7070 ~/heap.pprof
```
You will have to use the go toolchain, but this should allow you to visualize the profile at localhost:7070

@youngseoka

**Comment by youngseoka** [comment]
@nisdas I've been watching it constantly, but it's hard to determine what's the problem. Can you look at this screen and find a solution? Thank you always for your help.
[profile (2).pb.gz](https://github.com/OffchainLabs/eth-pos-devnet/files/11729485/profile.2.pb.gz)
![전체화면](https://github.com/OffchainLabs/eth-pos-devnet/assets/33947681/a13186ed-91f6-4f1f-9df3-e62a264a16fb)
![1111](https://github.com/OffchainLabs/eth-pos-devnet/assets/33947681/d82feebc-ef45-42fd-9fe8-54a243f5e977)
![222](https://github.com/OffchainLabs/eth-pos-devnet/assets/33947681/1437f95f-c882-42a6-b9b1-5892b12691ee)

**Comment by nisdas** [comment]
@youngseoka Maybe try running with `--minimum-peers-per-subnet=0`

**Comment by macrocan** [comment]
> 

it can work，memory usage is constant now

**Comment by DenkevichOleg** [comment]
> --minimum-peers-per-subnet=0

it produce errors from beacon-chain when node syncing 

```
time="2023-08-11 16:57:30" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=1 suitable=0
time="2023-08-11 16:57:30" level=debug msg="Peer has sent a goodbye message" Reason="fault/error" peer=16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt prefix=sync
time="2023-08-11 16:57:35" level=debug msg="No connections to peer, reconnecting" peer=16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt prefix=p2p
time="2023-08-11 16:57:35" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=1 suitable=0
time="2023-08-11 16:57:40" level=error msg="Failed to reconnect to peer" addrs=[/ip4/93.112.26.30/tcp/13000] error="failed to dial 16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt:
  * [/ip4/93.112.26.30/tcp/13000] failed to negotiate security protocol: read tcp4 172.28.0.3:13000->93.112.26.30:13000: read: connection reset by peer
  * [/ip4/172.21.0.2/tcp/13000] dial tcp4 172.28.0.3:13000->172.21.0.2:13000: i/o timeout" peer=16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt prefix=p2p
time="2023-08-11 16:57:40" level=debug msg="No connections to peer, reconnecting" peer=16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt prefix=p2p
time="2023-08-11 16:57:40" level=error msg="Failed to reconnect to peer" addrs=[/ip4/93.112.26.30/tcp/13000] error="failed to dial 16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt:
  * [/ip4/172.21.0.2/tcp/13000] dial backoff
  * [/ip4/93.112.26.30/tcp/13000] dial backoff" peer=16Uiu2HAm7T3ymZ3PbMn431TEqYjm7AAQc8oPGkQ9bzFqKHEw73zt prefix=p2p
time="2023-08-11 16:57:40" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=1 suitable=0
time="2023-08-11 16:57:40" level=debug msg="Latest eth1 chain event" blockHash=0x327105035ae9508552d020fff22872be890176e0f4ded2ea992ef60aba260893 blockNumber=0 prefix=powchain
time="2023-08-11 16:57:40" level=warning msg="Execution client is not syncing" prefix=powchain
```

**Comment by bilaljawed** [comment]
> @youngseoka Maybe try running with `--minimum-peers-per-subnet=0`

This causes peers not to connect then, even with subnet=1 it causes high memory consumption

**Comment by youngseoka** [comment]
thank you it work for me
