### ISSUE TITLE
does this work at all as of v4.0.6 and geth 1.12 ?

### ISSUE THREAD

**Issue by garyng2000** [OffchainLabs/eth-pos-devnet#24]
I follow the steps as outlined in the doc but it never work, tried both the docker approach as well as manually. it can never successfully switch to the post merge state

just stuck with this

ERROR blockchain: could not process new slot error=0x0000000000000000000000000000000000000000000000000000000000000000: unknown finalized root

and 
this
ERROR powchain: Unable to retrieve proof-of-stake genesis block data error=HeaderByHash, hash=0x4ae417863ba08901ea38c159e4fd210b952312338e999b8dd065de97c93a311f: not foun

**Comment by nisdas** [comment]
1.12 is breaking change @garyng2000 
https://github.com/ethereum/go-ethereum/releases/tag/v1.12.0

It removes the ability for us to run clique, so that will cause issues. Can you try downgrading your geth version here

**Comment by garyng2000** [comment]
Yes, I have tried a few different way like download older version of prysm(all the way back to 3.1.2)/geth(1.11/1.10) and even followed the blog post and download the specific commit(of prysm and geth) and still seeing similar issue which is that the CL side stopped at around block 25 due to the TTD config of 50 and both side knows that and started to communicate but cannot switch to POS mode with different error message depending on version of prysm/geth used

**Comment by nisdas** [comment]
Can you try Prysm v4.0.5 and Geth v1.11.3 with a completely fresh data directory.

**Comment by cihati** [comment]
@nisdas Related to this, I'd suggest _not_ using `latest` tag in docker-compose.yml and pinning to specific versions, so that we are protected against such changes.

**Comment by garyng2000** [comment]
> Can you try Prysm v4.0.5 and Geth v1.11.3 with a completely fresh data directory.

exact same error message in prysm beacon

ERROR blockchain: could not process new slot error=0x0000000000000000000000000000000000000000000000000000000000000000: unknown finalized root

**Comment by jkryanchou** [comment]
@garyng2000 cant agree with your more. 👍 @cihati I suggest that it's better to update the docker image tag to fix the issue :)

**Comment by aerielabio** [comment]
we tried gcr.io/prysmaticlabs/prysm/cmd/prysmctl:v4.0.5 but not working, or am i doing it wrong ?

> @nisdas Related to this, I'd suggest _not_ using `latest` tag in docker-compose.yml and pinning to specific versions, so that we are protected against such changes.

**Comment by nisdas** [comment]
@aerielabio Can we have more details, which part is not working ?

**Comment by icemagno** [comment]
Anybody knows why this error? One day this must be upgraded to a newer version.... Isn't better fix the error than freeze the version forever?

**Comment by icemagno** [comment]
Using HEAD-58df1f1 and v1.11.3 I confirm this issue still .

**Comment by noirgif** [comment]
> 1.12 is breaking change @garyng2000 https://github.com/ethereum/go-ethereum/releases/tag/v1.12.0
> 
> It removes the ability for us to run clique, so that will cause issues. Can you try downgrading your geth version here

It seems to have removed only `ethash`, not `clique`.
Also, we can set `"terminalTotalDifficultyPassed": true` in `genesis.json`, remove `clique: {...}` to make the execution chain starts from PoW.

**Comment by rauljordan** [comment]
Hi @noirgif and @garyng2000 fixed it up, try `make clean` and `docker compose up -d`

**Comment by garyng2000** [comment]
got this in the prysm genesis stage :-(

create-beacon-chain-genesis_1  | time="2023-10-24T22:23:21Z" level=info msg="Specified a chain config file: /consensus/config.yml" prefix=genesis
create-beacon-chain-genesis_1  | time="2023-10-24T22:23:21Z" level=info msg="No genesis time specified, defaulting to now()" prefix=genesis
create-beacon-chain-genesis_1  | time="2023-10-24T22:23:21Z" level=info msg="Delaying genesis 1698186201 by 15 seconds" prefix=genesis
create-beacon-chain-genesis_1  | time="2023-10-24T22:23:21Z" level=info msg="Genesis is now 1698186216" prefix=genesis
create-beacon-chain-genesis_1  | panic: runtime error: invalid memory address or nil pointer dereference
create-beacon-chain-genesis_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d0503f]
create-beacon-chain-genesis_1  |
create-beacon-chain-genesis_1  | goroutine 1 [running]:
create-beacon-chain-genesis_1  | github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.generateGenesis({0xcfacd0, 0xc00005c030})
create-beacon-chain-genesis_1  |        cmd/prysmctl/testnet/generate_genesis.go:279 +0x6ff
create-beacon-chain-genesis_1  | github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.cliActionGenerateGenesisState(0xc0003d2340)
create-beacon-chain-genesis_1  |        cmd/prysmctl/testnet/generate_genesis.go:179 +0x1c9
create-beacon-chain-genesis_1  | github.com/prysmaticlabs/prysm/v4/cmd/prysmctl/testnet.glob..func1(0x2fad200?)
create-beacon-chain-genesis_1  |        cmd/prysmctl/testnet/generate_genesis.go:70 +0x2e
create-beacon-chain-genesis_1  | github.com/urfave/cli/v2.(*Command).Run(0x2fad200, 0xc0003d2340, {0xc0003d8100, 0x8, 0x8})
create-beacon-chain-genesis_1  |        external/com_github_urfave_cli_v2/command.go:274 +0x9eb
create-beacon-chain-genesis_1  | github.com/urfave/cli/v2.(*Command).Run(0x2fad0a0, 0xc0003d2280, {0xc00024cbd0, 0x9, 0x9})
create-beacon-chain-genesis_1  |        external/com_github_urfave_cli_v2/command.go:267 +0xc4d
create-beacon-chain-genesis_1  | github.com/urfave/cli/v2.(*Command).Run(0xc0001f5e40, 0xc0003d21c0, {0xc0000520a0, 0xa, 0xa})
create-beacon-chain-genesis_1  |        external/com_github_urfave_cli_v2/command.go:267 +0xc4d
create-beacon-chain-genesis_1  | github.com/urfave/cli/v2.(*App).RunContext(0xc0003de000, {0xcfacd0?, 0xc00005c030}, {0xc0000520a0, 0xa, 0xa})
create-beacon-chain-genesis_1  |        external/com_github_urfave_cli_v2/app.go:332 +0x616
create-beacon-chain-genesis_1  | github.com/urfave/cli/v2.(*App).Run(...)
create-beacon-chain-genesis_1  |        external/com_github_urfave_cli_v2/app.go:309
create-beacon-chain-genesis_1  | main.main()
create-beacon-chain-genesis_1  |        cmd/prysmctl/main.go:23 +0x8e
