### ISSUE TITLE
How to start from PoS directly?

### ISSUE THREAD

**Issue by cihati** [OffchainLabs/eth-pos-devnet#25]
Hi,

currently, devnet starts at PoW, then switches to Bellatrix fork and at some point switches to Capella & PoS. For my testing setup, I want it to start from PoS + Capella right away. What settings do I need to change? Many thanks, cc @kasey @nisdas @rauljordan 🙏

**Comment by nisdas** [comment]
It should start directly from bellatrix as of the current commit @cihati in `eth-pos-devnet`

**Comment by cihati** [comment]
@nisdas But I think it still starts with PoW and then switches, right? I can see "Left PoW stage" and "Entered PoS stage"

1) If it still indeed start with PoW, how can I make it start with PoS?
1a) If it starts with PoS insted, I'd kindly suggest we get rid of the confusing messages above & update the README, as it's incorrect.

2) How can I start from Capella right away? Is there anything else to change, apart from changing `- --fork=bellatrix` line in docker-compose.yml ?

Thanks!

**Comment by nisdas** [comment]
To diagnose your issue, it would be helpful if you can paste your beacon logs here. It would be easier for us to find the issue with those logs.

On your 2nd point, just changing the fork in `prysmctl` should work. If it does not work, then let us know.

**Comment by cihati** [comment]
Re 2nd point: I also needed to change `CAPELLA_FORK_EPOCH: 2` to `0` in consensus/config.yml

Re 1: let me put some snippets:

```
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.236] Starting work on payload                 id=0x2b10d50c6ecd129b
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.237] Updated payload                          id=0x2b10d50c6ecd129b number=1 hash=8f8e40..4ee12f txs=0 withdrawals=0 gas=0 fees=0 root=815538..801014 elapsed="121.542µs"
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.239] Stopping work on payload                 id=0x2b10d50c6ecd129b reason=delivery
eth-pos-devnet-beacon-chain-1                 | time="2023-06-29 19:23:23" level=info msg="Finished building block" prefix="rpc/validator" sinceSlotStartTime=271.41616ms slot=1 validator=28
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.307] Imported new potential chain segment     number=1 hash=8f8e40..4ee12f blocks=1 txs=0 mgas=0.000 elapsed="138.468µs" mgasps=0.000 dirty=0.00B
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.307] Left PoW stage
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.314] Chain head was updated                   number=1 hash=8f8e40..4ee12f root=815538..801014 elapsed="47.037µs"
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.314] Starting work on payload                 id=0x5e660957e80152a8
eth-pos-devnet-geth-1                         | INFO [06-29|19:23:23.315] Updated payload                          id=0x5e660957e80152a8 number=2 hash=53f76b..8cb935 txs=0 withdrawals=0 gas=0 fees=0 root=815538..801014 elapsed="28.325µs"
eth-pos-devnet-beacon-chain-1                 | time="2023-06-29 19:23:23" level=info msg="Synced new block" block=0xcbeece16... epoch=0 finalizedEpoch=0 finalizedRoot=0x00000000... prefix=blockchain slot=1
eth-pos-devnet-beacon-chain-1                 | time="2023-06-29 19:23:23" level=info msg="Finished applying state transition" payloadHash=0x8f8e40b4e9a0 prefix=blockchain slot=1 syncBitsCount=512 txCount=0
eth-pos-devnet-validator-1                    | time="2023-06-29 19:23:23" level=info msg="Submitted new block" blockRoot=0xcbeece161acc fork=bellatrix gasUtilized=0 graffiti="" numAttestations=0 numDeposits=0 parentHash=0xc68095c0ba28 payloadHash=0x8f8e40b4e9a0 prefix=validator pubKey=0xb245d63d3f9d slot=1 txCount=0
eth-pos-devnet-validator-1                    | time="2023-06-29 19:23:27" level=info msg="Submitted new sync message" blockRoot=0xcbeece161acc prefix=validator slot=1 slotStartTime=2023-06-29 19:23:23 +0000 UTC timeSinceSlotStart=4.004372584s validatorIndex=20
```

As you can see, it says `Left PoW stage` (which arguably happens fairly quickly), before slot 1. I think README needs updating, basically.

**Comment by nisdas** [comment]
Yeah that log is cosmetic, it happens at genesis for geth. It just means there is no POW here as you are starting from bellatrix. Yes, we should update the readme for this

**Comment by garyng2000** [comment]
what is your setup that you can see this ? I can't even reach the beacon-chain sync state

**Comment by cihati** [comment]
@garyng2000 I'm using the normal `master` branch.

**Comment by rauljordan** [comment]
Hi @cihati this has now been fixed. It now starts from capella successfully
