### ISSUE TITLE
ERROR: for geth-genesis  Container "71fabd545295" exited with code 1.  ERROR: for beacon-chain  Container "71fabd545295" exited with code 1.

### ISSUE THREAD

**Issue by Gopal-Gurram** [OffchainLabs/eth-pos-devnet#35]
getting the below after using the repo and not able to create docker containers for the project?
Creating eth-pos-devnet_create-beacon-chain-genesis_1 ... done

ERROR: for geth-genesis  Container "71fabd545295" exited with code 1.

ERROR: for beacon-chain  Container "71fabd545295" exited with code 1.
ERROR: Encountered errors while bringing up the project.

**Comment by rauljordan** [comment]
Hi @Gopal-Gurram this should now be fixed. Pull the latest master and run `make clean` then `docker compose up -d` and everything should be operational. Let me know if this still persists and I can reopen
