### ISSUE TITLE
How to Stake with that contract?

### ISSUE THREAD

**Issue by KP-Universe** [OffchainLabs/eth-pos-devnet#45]
"The network launches with a Validator Deposit Contract deployed at address 0x4242424242424242424242424242424242424242. This can be used to onboard new validators into the network by depositing 32 ETH into the contract"
Where could I get deposit contract details.....

I just want to add validator by staking(maybe deposit to contract), but I can't find the detail process of that...

Could I get any contract method detail for deposit and withdraw???

**Comment by KP-Universe** [comment]
I used ethereal to deposit.

**Comment by cw760** [comment]
> I used ethereal to deposit.

I generated the deposit.json with [staking-deposit-cli](https://github.com/ethereum/staking-deposit-cli), and deleted the `"network_name": "mainnet",`, the use `ethereal validator deposit --data=deposit.json --connection=http://localhost:8545` --consensus-connection=http://localhost:3500 -- allow-unknown-contract --address=0x1234....abcd --from=0x1234... --privatekey=abcd... ` to deposit the 32ETH. 
Then I import the wallet with the keystone file generated by staking-deposit-cli. 
Then run `prysm.sh validator` with the `--wallet-dir`, how can I know my validator working?
