### ISSUE TITLE
service "create-beacon-chain-genesis" didn't complete successfully: exit 1

### ISSUE THREAD

**Issue by qymlyl** [OffchainLabs/eth-pos-devnet#51]
No modifications were made after cloning the project.
![image](https://github.com/OffchainLabs/eth-pos-devnet/assets/61776278/52220428-1757-48d5-9b50-f3e0f5d1041e)
![image](https://github.com/OffchainLabs/eth-pos-devnet/assets/61776278/4a330d08-dbea-417a-8250-bd73880bd49d)
![image](https://github.com/OffchainLabs/eth-pos-devnet/assets/61776278/7b9cff99-217d-4b0f-9be6-b0fb556df500)

**Comment by qymlyl** [comment]
see https://github.com/OffchainLabs/eth-pos-devnet/pull/50

**Comment by nx-tom** [comment]
see 2
