### ISSUE TITLE
Error: Could not process new slot, unknown finalized root" prefix=blockchain

### ISSUE THREAD

**Issue by john-risk-adigium** [OffchainLabs/eth-pos-devnet#7]
I am getting this error in the beacon chain logs:
`msg="Could not process new slot" error="0x0000000000000000000000000000000000000000000000000000000000000000: unknown finalized root" prefix=blockchain`

Am I missing some configuration?

**Comment by bxlkm** [comment]
same issue.

**Comment by rauljordan** [comment]
Fixed

**Comment by BrunoAura** [comment]
how was that fixed ? I still have it

**Comment by wawrzek** [comment]
@BrunoAura is it with the DockerDesktop (maybe even on MacOS)?
It works fine for Rancher Desktop, but not for Docker Desktop.
